### ISSUE TITLE
Rewrite configuration is applied to the registry fallback

### ISSUE THREAD

**Issue by rassie** [rancher/wharfie#25]
With the following configuration:

```json
{
    "mirrors": {
        "docker.io": {
            "endpoint": ["https://my.cool.registry"],
            "rewrite": {
                "^(.*)": "mirror-dockerhub/$1"
            }
        }
    }
}
```

calling `./wharfie --debug --private-registry registries.json scratch .` yields the following output:

```
INFO[0000] Extract mapping / => /tmp/wharfie-test 
INFO[0000] Using private registry config file at registries.json 
INFO[0000] Pulling image reference index.docker.io/library/scratch:latest 
DEBU[0000] Registry endpoint URL modified: https://index.docker.io/v2/ => https://my.cool.registry/v2/?ns=docker.io 
WARN[0000] Failed to get image from endpoint: Get "https://my.cool.registry/v2/?ns=docker.io": dial tcp: lookup my.cool.registry on 127.0.0.53:53: no such host 
WARN[0001] Failed to get image from endpoint: GET https://index.docker.io/v2/mirror-dockerhub/library/scratch/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:mirror-dockerhub/library/scratch Type:repository]] 
FATA[0001] Error: failed to get image reference index.docker.io/library/scratch:latest: all endpoints failed: Get "https://my.cool.registry/v2/?ns=docker.io": dial tcp: lookup my.cool.registry on 127.0.0.53:53: no such host; GET https://index.docker.io/v2/mirror-dockerhub/library/scratch/manifests/latest: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:mirror-dockerhub/library/scratch Type:repository]] 
```

As you can see, a pull from `https://index.docker.io/v2/` gets correctly rewritten to `https://my.cool.registry/v2/` (correct for this step, `mirror-dockerhub` prefix would get applied later). However, since `https://my.cool.registry/v2/` is not available, `wharfie` falls back to `https://index.docker.io/v2/`. In doing that, it applies the rewrite rule to the fallback registry, ending up with `https://index.docker.io/v2/mirror-dockerhub/library/scratch`, which is obviously not available to the general public (if by any happenstance at all).

Expectation: when falling back to the original registry, no rewriting should happen at all, since it's only valid for the mirrors.

**Comment by brandond** [comment]
This is kind of a defect in how rewrites are specified in registries.yaml. Ideally we would have structured this data a bit differently:
1. rewrites should be specified per endpoint, not per registry
2. rewrites should be an ordered list, instead of a map, as maps have no inherent order in golang so there is no guarantee that they are applied in the order specified in the yaml.

**Comment by brandond** [comment]
Related: https://github.com/k3s-io/k3s/blob/5c94ce2cf8c8c6c91e97801e3f6b699088e60f58/pkg/agent/containerd/config.go#L107-L111

**Comment by brandond** [comment]
We have since fixed this when generating mirror configs for containers; we should probably fix it here as well. I will note that some folks have already complained about this change, as they did want to use rewrites on the default endpoint 🤷‍♂️
