### ISSUE TITLE
Provide pull and save equivalent

### ISSUE THREAD

**Issue by laurivosandi** [rancher/wharfie#31]
K3s automatically picks up tarballs under /var/lib/rancher/k3s/agent/images/ and makes them available for the container runtime on that host

We're currently using `docker pull --platform ... foobar` and `docker save foobar | zstd > foobar.tar.zstd` to prepare the images but this places hard dependency on Docker daemon.

Looks like Wharfie could support pulling and storing the images as tarballs for such scenario as well

**Comment by brandond** [comment]
wharfie is meant to be used to unpack the contents of images, not for creating tarballs OF images. If you need this, I would look at other tools like https://github.com/containers/skopeo or https://github.com/google/go-containerregistry
